name: Build and Deploy to AWS

on:
  push:
    branches: [ "master" ]

env:
  IMAGE_NAME: yuanverse/customer_churn_repo_public   # Format: <dockerhub_account>/<repo>
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        
      - name: Build and tag Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Publish Docker image to Docker Hub
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest

  deploy-docker-image:
    runs-on: ubuntu-latest
    needs: [build-and-publish-docker-image]  # requires successful completion
    steps:
      - name: Set up SSH connection to AWS remote server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh/
          echo "${SSH_KEY}" > ~/.ssh/key.pem
          chmod 400 ~/.ssh/key.pem
          cat >> ~/.ssh/config << END
          Host remote_host
            HostName ${SSH_HOST}
            User ${SSH_USERNAME}
            IdentityFile ~/.ssh/key.pem
            StrictHostKeyChecking no
          END
      
      # - name: Install Docker on AWS remote machine
      #   run: ssh remote_host "sudo yum update -y && sudo yum install -y docker"

      # - name: Grant privileges to ec2-user
      #   run: ssh remote_host "sudo usermod -a -G docker ec2-user"

      # - name: Log out and log back in again
      #   run: exit

      # - name: Log in to EC2 instance again
      #   run: ssh -i ~/.ssh/ai300-capstone.pem ec2-user@${{ secrets.SSH_HOST }}

      - name: Deploy Docker container on AWS via SSH
        run: |  # Pre-requisite: docker has been installed on remote machine
          ssh remote_host "docker ps -a"                         # remote_host as defined in ~/.ssh/config
          ssh remote_host "docker ps -q | xargs -r docker stop"  # stops any running container
          ssh remote_host "docker pull ${IMAGE_NAME}"
          ssh remote_host "docker run -d -p 80:80 ${IMAGE_NAME}:latest"